// frontend/src/components/Footer.tsx
export default function Footer() {
  const currentYear = new Date().getFullYear()

  const footerSections = [
    {
      title: 'Tech Affairs',
      content: (
        <p className="text-brand-200 leading-relaxed">
          Complete technology solutions from software to hardware. Building the future, one project at a time.
        </p>
      )
    },
    {
      title: 'Quick Links',
      links: [
        { text: 'Home', href: '#home' },
        { text: 'Services', href: '#services' },
        { text: 'Projects', href: '#projects' },
        { text: 'About', href: '#about' },
        { text: 'Contact', href: '#contact' }
      ]
    },
    {
      title: 'Services',
      links: [
        { text: 'Software Development', href: '#services' },
        { text: 'Hardware Repairs', href: '#services' },
        { text: 'IoT Solutions', href: '#services' },
        { text: 'Training & Consulting', href: '#services' }
      ]
    },
    {
      title: 'Connect',
      links: [
        { text: 'LinkedIn', href: '#' },
        { text: 'GitHub', href: '#' },
        { text: 'Twitter', href: '#' }
      ]
    }
  ]

  return (
    <footer className="bg-brand-900 text-white py-12">
      <div className="max-w-7xl mx-auto px-6 lg:px-8">
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8 mb-8">
          {footerSections.map((section, index) => (
            <div key={index}>
              <h3 className="text-brand-300 font-semibold text-lg mb-4">
                {section.title}
              </h3>
              {section.content ? (
                section.content
              ) : (
                <ul className="space-y-2">
                  {section.links?.map((link, i) => (
                    <li key={i}>
                      <a 
                        href={link.href}
                        target={link.href.startsWith('http') ? '_blank' : undefined}
                        rel={link.href.startsWith('http') ? 'noopener noreferrer' : undefined}
                        className="text-brand-200 hover:text-brand-300 transition-colors"
                      >
                        {link.text}
                      </a>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          ))}
        </div>

        <div className="border-t border-brand-700 pt-8 text-center text-brand-300">
          <p>&copy; {currentYear} Tech Affairs & Innovative Hub. All rights reserved.</p>
        </div>
      </div>
    </footer>
  )
}

// frontend_vue/src/components/Footer.vue
<template>
  <footer class="bg-gray-900 text-gray-300">
    <div class="max-w-7xl mx-auto px-6 py-12 grid md:grid-cols-3 gap-8">

      <!-- Brand -->
      <div>
        <h3 class="text-lg font-semibold text-white mb-2">
          Tech Affairs & Innovative Hub
        </h3>
        <p class="text-sm text-gray-400">
          Complete technology solutions — software, hardware, and systems.
        </p>
      </div>

      <!-- Links -->
      <div>
        <h4 class="font-semibold text-white mb-3">Company</h4>
        <ul class="space-y-2 text-sm">
          <li><RouterLink to="/about" class="hover:text-white">About</RouterLink></li>
          <li><RouterLink to="/services" class="hover:text-white">Services</RouterLink></li>
          <li><RouterLink to="/projects" class="hover:text-white">Projects</RouterLink></li>
        </ul>
      </div>

      <!-- Contact -->
      <div>
        <h4 class="font-semibold text-white mb-3">Contact</h4>
        <p class="text-sm">Ibadan, Nigeria</p>
        <p class="text-sm">techaffairsandinnovation@gmail.com</p>
        <p class="text-sm">08059597963</p>
      </div>

    </div>

    <div class="border-t border-gray-800 text-center py-4 text-sm text-gray-500">
      © {{ new Date().getFullYear() }} Tech Affairs & Innovative Hub. All rights reserved.
    </div>
  </footer>
</template>
